// This is a Javascript test harness that simulates the execution of Lambda function code
// From the command prompt, type "node test.js"

let AWS = require('aws-sdk');
AWS.config.region = process.env.AWS_REGION || 'us-east-1';

const MyLambdaFunction = require('../lambda/custom/index.js'); // assumes single Lambda function with exports.handler

 // this is the Lambda request data, generated by the Alexa service.  Replace with your actual Alexa request.
const LaunchRequestEvent =
    {
        "version": "1.0",
        "session": {
            "new": true,
            "sessionId": "amzn1.echo-api.session.5dc8f547-44bf-4f7b-bce6-e00e841fe9ff",
            "application": {
                "applicationId": "amzn1.ask.skill.50ef6df2-ffb8-4692-8e18-c9b485cc03b0"
            },
            "user": {
                "userId": "amzn1.ask.account.AG4BEMGBJIJYRAGKP5YLYGJDISRIQVPWOEABD3OQW66MTPOF4JRHLAEETH5TBIOT652I3KUYZSWA5MAZ55GUTIBLEMUQ4YQBPKXVG4YSFHLQL27UEC6YQDXTEYH5MD4NMK4M7UJ4FWTRPKTSII4R733EX3TVC3UKLKOBMHXXM5CHOX2TDUV2WPF6NCWF5KLJETNGQ5YC7EOUFLO"
            }
        },
        "context": {
            "AudioPlayer": {
                "playerActivity": "IDLE"
            },
            "Display": {
                "token": ""
            },
            "System": {
                "application": {
                    "applicationId": "amzn1.ask.skill.50ef6df2-ffb8-4692-8e18-c9b485cc03b0"
                },
                "user": {
                    "userId": "amzn1.ask.account.AG4BEMGBJIJYRAGKP5YLYGJDISRIQVPWOEABD3OQW66MTPOF4JRHLAEETH5TBIOT652I3KUYZSWA5MAZ55GUTIBLEMUQ4YQBPKXVG4YSFHLQL27UEC6YQDXTEYH5MD4NMK4M7UJ4FWTRPKTSII4R733EX3TVC3UKLKOBMHXXM5CHOX2TDUV2WPF6NCWF5KLJETNGQ5YC7EOUFLO"
                },
                "device": {
                    "deviceId": "amzn1.ask.device.AFUWNBZ2FSMDFRJDWWA7GSZQBYX4DBS52RV7CHECNUTBCVMT6WW5SVO56SLUZ6D6TIJM5J2S6XNXKHAUU2RCXXQKUI75C37IOPVAA6HCVK5E5NV5EBVC5YUFAMIGD4FYZ4XFA4OEPDNCJYCHXN2RRGDQOZYQ",
                    "supportedInterfaces": {
                        "AudioPlayer": {},
                        "Display": {
                            "templateVersion": "1.0",
                            "markupVersion": "1.0"
                        }
                    }
                },
                "apiEndpoint": "https://api.amazonalexa.com",
                "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjUwZWY2ZGYyLWZmYjgtNDY5Mi04ZTE4LWM5YjQ4NWNjMDNiMCIsImV4cCI6MTUyMjcwOTI2OSwiaWF0IjoxNTIyNzA1NjY5LCJuYmYiOjE1MjI3MDU2NjksInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUZVV05CWjJGU01ERlJKRFdXQTdHU1pRQllYNERCUzUyUlY3Q0hFQ05VVEJDVk1UNldXNVNWTzU2U0xVWjZENlRJSk01SjJTNlhOWEtIQVVVMlJDWFhRS1VJNzVDMzdJT1BWQUE2SENWSzVFNU5WNUVCVkM1WVVGQU1JR0Q0RllaNFhGQTRPRVBETkNKWUNIWE4yUlJHRFFPWllRIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUc0QkVNR0JKSUpZUkFHS1A1WUxZR0pESVNSSVFWUFdPRUFCRDNPUVc2Nk1UUE9GNEpSSExBRUVUSDVUQklPVDY1MkkzS1VZWlNXQTVNQVo1NUdVVElCTEVNVVE0WVFCUEtYVkc0WVNGSExRTDI3VUVDNllRRFhURVlINU1ENE5NSzRNN1VKNEZXVFJQS1RTSUk0UjczM0VYM1RWQzNVS0xLT0JNSFhYTTVDSE9YMlREVVYyV1BGNk5DV0Y1S0xKRVROR1E1WUM3RU9VREJBIn19.dPbWxnmKZb-KCCDIFayLc7JkuFI1LQGsmHPvHMHAX4dnAwO0PmjGejdl-rlTwjXcIIPIDPT5Y65dIIf0D63SgVIYe2LC0M5alW327UhT5FVjJu8TmtEbiPEoVwKYWqmMbGYi95Zyi5q9XFGRTq6u9idaDALZLT7LjBdY_DQLmks5fSeI819n1AGuxPecwCO29s0GRHg6JNrLVyCsovJIMB0_9yvz_KoOzwXOHp9YfkA9jtOkBWuEjXe1_DKq1HM5VfuAyiTrM1IYmfw9yoctVcH2xCfqL0QmmIYL9TCuh3mTd3yK5S-0NC-uFijeT-Qyg0o6hjmr2v0zfG0NgHQpQA"
            }
        },
        "request": {
            "type": "LaunchRequest",
            "requestId": "amzn1.echo-api.request.867666fb-94f9-4ca7-aa08-2e886522e8ab",
            "timestamp": "2018-04-02T21:47:49Z",
            "locale": "en-US",
            "shouldLinkResultBeReturned": false
        }
    };

const FloTest =
    {
        "context": {
            "AudioPlayer": {
                "playerActivity": "IDLE"
            },
            "Display": {
                "token": ""
            },
            "System": {
                "application": {
                    "applicationId": "amzn1.ask.skill.50ef6df2-ffb8-4692-8e18-c9b485cc03b0"
                },
                "user": {
                    "userId": "amzn1.ask.account.AG4BEMGBJIJYRAGKP5YLYGJDISRIQVPWOEABD3OQW66MTPOF4JRHLAEETH5TBIOT652I3KUYZSWA5MAZ55GUTIBLEMUQ4YQBPKXVG4YSFHLQL27UEC6YQDXTEYH5MD4NMK4M7UJ4FWTRPKTSII4R733EX3TVC3UKLKOBMHXXM5CHOX2TDUV2WPF6NCWF5KLJETNGQ5YC7EOUFLO"
                },
                "device": {
                    "deviceId": "amzn1.ask.device.AFUWNBZ2FSMDFRJDWWA7GSZQBYX4DBS52RV7CHECNUTBCVMT6WW5SVO56SLUZ6D6TIJM5J2S6XNXKHAUU2RCXXQKUI75C37IOPVAA6HCVK5E5NV5EBVC5YUFAMIGD4FYZ4XFA4OEPDNCJYCHXN2RRGDQOZYQ",
                    "supportedInterfaces": {
                        "AudioPlayer": {},
                        "Display": {
                            "templateVersion": "1.0",
                            "markupVersion": "1.0"
                        }
                    }
                },
                "apiEndpoint": "https://api.amazonalexa.com",
                "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjUwZWY2ZGYyLWZmYjgtNDY5Mi04ZTE4LWM5YjQ4NWNjMDNiMCIsImV4cCI6MTUyMjcwOTI2OSwiaWF0IjoxNTIyNzA1NjY5LCJuYmYiOjE1MjI3MDU2NjksInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUZVV05CWjJGU01ERlJKRFdXQTdHU1pRQllYNERCUzUyUlY3Q0hFQ05VVEJDVk1UNldXNVNWTzU2U0xVWjZENlRJSk01SjJTNlhOWEtIQVVVMlJDWFhRS1VJNzVDMzdJT1BWQUE2SENWSzVFNU5WNUVCVkM1WVVGQU1JR0Q0RllaNFhGQTRPRVBETkNKWUNIWE4yUlJHRFFPWllRIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUc0QkVNR0JKSUpZUkFHS1A1WUxZR0pESVNSSVFWUFdPRUFCRDNPUVc2Nk1UUE9GNEpSSExBRUVUSDVUQklPVDY1MkkzS1VZWlNXQTVNQVo1NUdVVElCTEVNVVE0WVFCUEtYVkc0WVNGSExRTDI3VUVDNllRRFhURVlINU1ENE5NSzRNN1VKNEZXVFJQS1RTSUk0UjczM0VYM1RWQzNVS0xLT0JNSFhYTTVDSE9YMlREVVYyV1BGNk5DV0Y1S0xKRVROR1E1WUM3RU9VREJBIn19.dPbWxnmKZb-KCCDIFayLc7JkuFI1LQGsmHPvHMHAX4dnAwO0PmjGejdl-rlTwjXcIIPIDPT5Y65dIIf0D63SgVIYe2LC0M5alW327UhT5FVjJu8TmtEbiPEoVwKYWqmMbGYi95Zyi5q9XFGRTq6u9idaDALZLT7LjBdY_DQLmks5fSeI819n1AGuxPecwCO29s0GRHg6JNrLVyCsovJIMB0_9yvz_KoOzwXOHp9YfkA9jtOkBWuEjXe1_DKq1HM5VfuAyiTrM1IYmfw9yoctVcH2xCfqL0QmmIYL9TCuh3mTd3yK5S-0NC-uFijeT-Qyg0o6hjmr2v0zfG0NgHQpQA"
            }
        },
        "session": {
            "sessionId": "SessionId.f9e6dcbb-b7da-4b47-905c.etc.etc",
            "application": {
                "applicationId": "amzn1.echo-sdk-ams.app.1234"
            },
            "attributes": {},
            "user": {
                "userId": "amzn1.ask.account.AG4BEMGBJIJYRAGKP5YLYGJDISRIQVPWOEABD3OQW66MTPOF4JRHLAEETH5TBIOT652I3KUYZSWA5MAZ55GUTIBLEMUQ4YQBPKXVG4YSFHLQL27UEC6YQDXTEYH5MD4NMK4M7UJ4FWTRPKTSII4R733EX3TVC3UKLKOBMHXXM5CHOX2TDUV2WPF6NCWF5KLJETNGQ5YC7EOUFLO"
            },
            "new": true
        },
        "request": {
            "type": "LaunchRequest",
            "locale": "en-US",
            "timestamp": "2018-04-03T21:47:49Z"
        },
        "version": "1.0"
    };

const MyNameIsIntent =
    {
        "version": "1.0",
        "session": {
            "new": true,
            "sessionId": "amzn1.echo-api.session.c3b5d172-e277-4b5e-8d06-19c0a84d0dde",
            "application": {
                "applicationId": "amzn1.ask.skill.50ef6df2-ffb8-4692-8e18-c9b485cc03b0"
            },
            "attributes": {
                "launchCount": 4,
                "zip": null,
                "country": null,
                "namePronounce": null,
                "address2": null,
                "city": null,
                "address1": null,
                "mobile": null,
                "lastIntent": {},
                "favoriteColor": null,
                "history": [],
                "enabled": true,
                "bookmark": 0,
                "name": "Robert",
                "state": null,
                "preferredGreeting": "welcome",
                "email": null,
                "lastSession": null,
                "lastUseTimestamp": 0
            },
            "user": {
                "userId": "amzn1.ask.account.AG4BEMGBJIJYRAGKP5YLYGJDISRIQVPWOEABD3OQW66MTPOF4JRHLAEETH5TBIOT652I3KUYZSWA5MAZ55GUTIBLEMUQ4YQBPKXVG4YSFHLQL27UEC6YQDXTEYH5MD4NMK4M7UJ4FWTRPKTSII4R733EX3TVC3UKLKOBMHXXM5CHOX2TDUV2WPF6NCWF5KLJETNGQ5YC7EOUYYY"
            }
        },
        "context": {
            "AudioPlayer": {
                "playerActivity": "IDLE"
            },
            "Display": {
                "token": ""
            },
            "System": {
                "application": {
                    "applicationId": "amzn1.ask.skill.50ef6df2-ffb8-4692-8e18-c9b485cc03b0"
                },
                "user": {
                    "userId": "amzn1.ask.account.AG4BEMGBJIJYRAGKP5YLYGJDISRIQVPWOEABD3OQW66MTPOF4JRHLAEETH5TBIOT652I3KUYZSWA5MAZ55GUTIBLEMUQ4YQBPKXVG4YSFHLQL27UEC6YQDXTEYH5MD4NMK4M7UJ4FWTRPKTSII4R733EX3TVC3UKLKOBMHXXM5CHOX2TDUV2WPF6NCWF5KLJETNGQ5YC7EOUYYY"
                },
                "device": {
                    "deviceId": "amzn1.ask.device.AFUWNBZ2FSMDFRJDWWA7GSZQBYX4DBS52RV7CHECNUTBCVMT6WW5SVO56SLUZ6D6TIJM5J2S6XNXKHAUU2RCXXQKUI75C37IOPVAA6HCVK5E5NV5EBVC5YUFAMIGD4FYZ4XFA4OEPDNCJYCHXN2RRGDQOZYQ",
                    "supportedInterfaces": {
                        "AudioPlayer": {},
                        "Display": {
                            "templateVersion": "1.0",
                            "markupVersion": "1.0"
                        }
                    }
                },
                "apiEndpoint": "https://api.amazonalexa.com",
                "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjUwZWY2ZGYyLWZmYjgtNDY5Mi04ZTE4LWM5YjQ4NWNjMDNiMCIsImV4cCI6MTUyMjcwOTE2MywiaWF0IjoxNTIyNzA1NTYzLCJuYmYiOjE1MjI3MDU1NjMsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUZVV05CWjJGU01ERlJKRFdXQTdHU1pRQllYNERCUzUyUlY3Q0hFQ05VVEJDVk1UNldXNVNWTzU2U0xVWjZENlRJSk01SjJTNlhOWEtIQVVVMlJDWFhRS1VJNzVDMzdJT1BWQUE2SENWSzVFNU5WNUVCVkM1WVVGQU1JR0Q0RllaNFhGQTRPRVBETkNKWUNIWE4yUlJHRFFPWllRIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUc0QkVNR0JKSUpZUkFHS1A1WUxZR0pESVNSSVFWUFdPRUFCRDNPUVc2Nk1UUE9GNEpSSExBRUVUSDVUQklPVDY1MkkzS1VZWlNXQTVNQVo1NUdVVElCTEVNVVE0WVFCUEtYVkc0WVNGSExRTDI3VUVDNllRRFhURVlINU1ENE5NSzRNN1VKNEZXVFJQS1RTSUk0UjczM0VYM1RWQzNVS0xLT0JNSFhYTTVDSE9YMlREVVYyV1BGNk5DV0Y1S0xKRVROR1E1WUM3RU9VREJBIn19.B9C-lNawO5m22Y5wUOi8_F3gkc4q_A58hJq_jChs1SP2bbMWOptD7aVMyp7VCkjQH8sER809D1_K23Ur_kDpnGJSDZICm4Ka4Kk7Q-h4yyNcqzAJEV-MdsNwfi_as2tc8dbTSjey9w1uww2ebnVKTENfc3oON6WavCrTfL8zFEZBOmy74XGDACBDDHuZJ2jSGgSdP_2kbih_Q1CxdtsYGcFer4Tm0jjrtZlQkXoSD79CAuRs5wb5baBOAtFJid_3NToNdp98DdgJXRwFSC1Fo132QOjWktmkiL7UeBZkuT4636PAP_n0odd_V9KJX8jZ9M6wa8iMAjX1uEEFCSwjmA"
            }
        },
        "request": {
            "type": "IntentRequest",
            "requestId": "amzn1.echo-api.request.efe3f6bb-2dc1-467d-8ea9-7059acbcb8b3",
            "timestamp": "2018-04-02T21:46:03Z",
            "locale": "en-US",
            "intent": {
                "name": "MyNameIsIntent",
                "confirmationStatus": "NONE",
                "slots": {
                    "firstname": {
                        "name": "firstname",
                        "value": "Harry",
                        "confirmationStatus": "NONE"
                    }
                }
            }
        }
    };
const StatusIntent =
    {
        "version": "1.0",
        "session": {
            "new": false,
            "sessionId": "amzn1.echo-api.session.1c8fb15e-d600-4745-a90f-70430b7d27ff",
            "application": {
                "applicationId": "amzn1.ask.skill.50ef6df2-ffb8-4692-8e18-c9b485cc03b0"
            },
            "attributes": {
                "launchCount": 42,
                "zip": null,
                "country": null,
                "namePronounce": null,
                "address2": null,
                "city": null,
                "address1": null,
                "mobile": null,
                "lastIntent": {},
                "favoriteColor": null,
                "history": [],
                "enabled": true,
                "bookmark": 0,
                "name": "Richard",
                "state": null,
                "preferredGreeting": "welcome",
                "email": null,
                "lastSession": null,
                "lastUseTimestamp": 1522735424000
            },
            "user": {
                "userId": "amzn1.ask.account.AG4BEMGBJIJYRAGKP5YLYGJDISRIQVPWOEABD3OQW66MTPOF4JRHLAEETH5TBIOT652I3KUYZSWA5MAZ55GUTIBLEMUQ4YQBPKXVG4YSFHLQL27UEC6YQDXTEYH5MD4NMK4M7UJ4FWTRPKTSII4R733EX3TVC3UKLKOBMHXXM5CHOX2TDUV2WPF6NCWF5KLJETNGQ5YC7EOUDBA"
            }
        },
        "context": {
            "AudioPlayer": {
                "playerActivity": "IDLE"
            },
            "Display": {
                "token": ""
            },
            "System": {
                "application": {
                    "applicationId": "amzn1.ask.skill.50ef6df2-ffb8-4692-8e18-c9b485cc03b0"
                },
                "user": {
                    "userId": "amzn1.ask.account.AG4BEMGBJIJYRAGKP5YLYGJDISRIQVPWOEABD3OQW66MTPOF4JRHLAEETH5TBIOT652I3KUYZSWA5MAZ55GUTIBLEMUQ4YQBPKXVG4YSFHLQL27UEC6YQDXTEYH5MD4NMK4M7UJ4FWTRPKTSII4R733EX3TVC3UKLKOBMHXXM5CHOX2TDUV2WPF6NCWF5KLJETNGQ5YC7EOUDBA"
                },
                "device": {
                    "deviceId": "amzn1.ask.device.AFUWNBZ2FSMDFRJDWWA7GSZQBYX4DBS52RV7CHECNUTBCVMT6WW5SVO56SLUZ6D6TIJM5J2S6XNXKHAUU2RCXXQKUI75C37IOPVAA6HCVK5E5NV5EBVC5YUFAMIGD4FYZ4XFA4OEPDNCJYCHXN2RRGDQOZYQ",
                    "supportedInterfaces": {
                        "AudioPlayer": {},
                        "Display": {
                            "templateVersion": "1.0",
                            "markupVersion": "1.0"
                        }
                    }
                },
                "apiEndpoint": "https://api.amazonalexa.com",
                "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjUwZWY2ZGYyLWZmYjgtNDY5Mi04ZTE4LWM5YjQ4NWNjMDNiMCIsImV4cCI6MTUyMjczOTEzNiwiaWF0IjoxNTIyNzM1NTM2LCJuYmYiOjE1MjI3MzU1MzYsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUZVV05CWjJGU01ERlJKRFdXQTdHU1pRQllYNERCUzUyUlY3Q0hFQ05VVEJDVk1UNldXNVNWTzU2U0xVWjZENlRJSk01SjJTNlhOWEtIQVVVMlJDWFhRS1VJNzVDMzdJT1BWQUE2SENWSzVFNU5WNUVCVkM1WVVGQU1JR0Q0RllaNFhGQTRPRVBETkNKWUNIWE4yUlJHRFFPWllRIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUc0QkVNR0JKSUpZUkFHS1A1WUxZR0pESVNSSVFWUFdPRUFCRDNPUVc2Nk1UUE9GNEpSSExBRUVUSDVUQklPVDY1MkkzS1VZWlNXQTVNQVo1NUdVVElCTEVNVVE0WVFCUEtYVkc0WVNGSExRTDI3VUVDNllRRFhURVlINU1ENE5NSzRNN1VKNEZXVFJQS1RTSUk0UjczM0VYM1RWQzNVS0xLT0JNSFhYTTVDSE9YMlREVVYyV1BGNk5DV0Y1S0xKRVROR1E1WUM3RU9VREJBIn19.Oh4a2imdHoNirUxvvnXAo3GUalbD5_lsIYvJp0ZuLz38XA2YHNw233_m5OFJEcxLO1kiDOXF8oWHkyfpbfxgvBuezBTS9m21oLSc47EiD0ZYYxREJipS2sp4bJXXdNuOHnHNaXPKMk3Ny8vZwoJDUs85CbyKt-dNLj6VvxaWiNAZTi0wgkoKLkWLm492xKBbSTD_Vp0A_eGYqKzBmtrbPu2_P5im6YDxE6lefvDTgeoKUtRIV3_7zbkGT6VneWay0r6mHRdQjBJ5oPu4JGjbS-40Ls1-kB7H_SKOHM2qeN1TK80XvJq9dJB2eiwJExyItH3gkq1HSmH4X1GEeR84FA"
            }
        },
        "request": {
            "type": "IntentRequest",
            "requestId": "amzn1.echo-api.request.2f444344-17f0-48f4-a76f-91de3754edba",
            "timestamp": "2018-04-03T06:05:36Z",
            "locale": "en-US",
            "intent": {
                "name": "StatusIntent",
                "confirmationStatus": "NONE"
            }
        }
    };
const MyColorIsIntent =
    {
        "version": "1.0",
        "session": {
            "new": false,
            "sessionId": "amzn1.echo-api.session.cfb23921-fc22-4acf-af4c-776c761d8630",
            "application": {
                "applicationId": "amzn1.ask.skill.50ef6df2-ffb8-4692-8e18-c9b485cc03b0"
            },
            "attributes": {
                "launchCount": 41,
                "zip": null,
                "country": null,
                "namePronounce": null,
                "address2": null,
                "city": null,
                "address1": null,
                "mobile": null,
                "lastIntent": {},
                "favoriteColor": null,
                "history": [],
                "enabled": true,
                "bookmark": 0,
                "name": "Richard",
                "state": null,
                "preferredGreeting": "welcome",
                "email": null,
                "lastSession": null,
                "lastUseTimestamp": 1522733841000
            },
            "user": {
                "userId": "amzn1.ask.account.AG4BEMGBJIJYRAGKP5YLYGJDISRIQVPWOEABD3OQW66MTPOF4JRHLAEETH5TBIOT652I3KUYZSWA5MAZ55GUTIBLEMUQ4YQBPKXVG4YSFHLQL27UEC6YQDXTEYH5MD4NMK4M7UJ4FWTRPKTSII4R733EX3TVC3UKLKOBMHXXM5CHOX2TDUV2WPF6NCWF5KLJETNGQ5YC7EOUDBA"
            }
        },
        "context": {
            "AudioPlayer": {
                "playerActivity": "IDLE"
            },
            "Display": {
                "token": ""
            },
            "System": {
                "application": {
                    "applicationId": "amzn1.ask.skill.50ef6df2-ffb8-4692-8e18-c9b485cc03b0"
                },
                "user": {
                    "userId": "amzn1.ask.account.AG4BEMGBJIJYRAGKP5YLYGJDISRIQVPWOEABD3OQW66MTPOF4JRHLAEETH5TBIOT652I3KUYZSWA5MAZ55GUTIBLEMUQ4YQBPKXVG4YSFHLQL27UEC6YQDXTEYH5MD4NMK4M7UJ4FWTRPKTSII4R733EX3TVC3UKLKOBMHXXM5CHOX2TDUV2WPF6NCWF5KLJETNGQ5YC7EOUDBA"
                },
                "device": {
                    "deviceId": "amzn1.ask.device.AFUWNBZ2FSMDFRJDWWA7GSZQBYX4DBS52RV7CHECNUTBCVMT6WW5SVO56SLUZ6D6TIJM5J2S6XNXKHAUU2RCXXQKUI75C37IOPVAA6HCVK5E5NV5EBVC5YUFAMIGD4FYZ4XFA4OEPDNCJYCHXN2RRGDQOZYQ",
                    "supportedInterfaces": {
                        "AudioPlayer": {},
                        "Display": {
                            "templateVersion": "1.0",
                            "markupVersion": "1.0"
                        }
                    }
                },
                "apiEndpoint": "https://api.amazonalexa.com",
                "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjUwZWY2ZGYyLWZmYjgtNDY5Mi04ZTE4LWM5YjQ4NWNjMDNiMCIsImV4cCI6MTUyMjczNzcxOSwiaWF0IjoxNTIyNzM0MTE5LCJuYmYiOjE1MjI3MzQxMTksInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUZVV05CWjJGU01ERlJKRFdXQTdHU1pRQllYNERCUzUyUlY3Q0hFQ05VVEJDVk1UNldXNVNWTzU2U0xVWjZENlRJSk01SjJTNlhOWEtIQVVVMlJDWFhRS1VJNzVDMzdJT1BWQUE2SENWSzVFNU5WNUVCVkM1WVVGQU1JR0Q0RllaNFhGQTRPRVBETkNKWUNIWE4yUlJHRFFPWllRIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUc0QkVNR0JKSUpZUkFHS1A1WUxZR0pESVNSSVFWUFdPRUFCRDNPUVc2Nk1UUE9GNEpSSExBRUVUSDVUQklPVDY1MkkzS1VZWlNXQTVNQVo1NUdVVElCTEVNVVE0WVFCUEtYVkc0WVNGSExRTDI3VUVDNllRRFhURVlINU1ENE5NSzRNN1VKNEZXVFJQS1RTSUk0UjczM0VYM1RWQzNVS0xLT0JNSFhYTTVDSE9YMlREVVYyV1BGNk5DV0Y1S0xKRVROR1E1WUM3RU9VREJBIn19.GL4TO1895bB4ipphrFQ7g16IEZIuNVlJI4szEhIxTi-9GeOG1rvDBvJSoEgPd1eADL0kdF_eGJ-Yy4lEZAjQuq9tCnQSeEwzi2CzPmy6Z8Zoa28BayTbrm8R9CdC-1q5E1kUvsy2qc_O2R-smfA_RTsRb2n27Sw6NfbNdoZ08fls0GBhITjqpQ1YMKe5QUy_ypE345t-y8u_A1Lj8ldi8Dnmy6wY_OdNomFcZ40DX8atMWJBavOK53vFHiDka3g7FQiUdxusbccjgjQRzyrOljKTURIe2SJGSLvGUQEdU6X2zDBLifRvTnClxp5lgotqh8xUr24sqLFtuJsGtBD8CA"
            }
        },
        "request": {
            "type": "IntentRequest",
            "requestId": "amzn1.echo-api.request.cb7c15e4-195b-42d0-8d1a-83d1b99d1b91",
            "timestamp": "2018-04-03T05:41:59Z",
            "locale": "en-US",
            "intent": {
                "name": "MyColorIsIntent",
                "confirmationStatus": "NONE",
                "slots": {
                    "color": {
                        "name": "color",
                        "value": "green",
                        "resolutions": {
                            "resolutionsPerAuthority": [
                                {
                                    "authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.50ef6df2-ffb8-4692-8e18-c9b485cc03b0.ColorSlotType",
                                    "status": {
                                        "code": "ER_SUCCESS_MATCH"
                                    },
                                    "values": [
                                        {
                                            "value": {
                                                "name": "green",
                                                "id": "9f27410725ab8cc8854a2769c7a516b8"
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        "confirmationStatus": "NONE"
                    }
                }
            }
        }
    };

const CrimsonColorIntent =
    {
        "version": "1.0",
        "session": {
            "new": false,
            "sessionId": "amzn1.echo-api.session.96fb5b0a-a83c-408d-8364-3891eddad9a2",
            "application": {
                "applicationId": "amzn1.ask.skill.50ef6df2-ffb8-4692-8e18-c9b485cc03b0"
            },
            "attributes": {
                "launchCount": 2,
                "country": null,
                "namePronounce": null,
                "mobile": null,
                "lastIntent": {},
                "favoriteColor": "orange",
                "history": [
                    {
                        "IntentRequest": "LaunchRequest"
                    },
                    {
                        "IntentRequest": "LaunchRequest"
                    },
                    {
                        "IntentRequest": "MyNameIsIntent"
                    },
                    {
                        "IntentRequest": "MyColorIsIntent"
                    },
                    {
                        "IntentRequest": "StatusIntent"
                    },
                    {
                        "IntentRequest": "AMAZON.StopIntent"
                    },
                    {
                        "IntentRequest": "LaunchRequest"
                    }
                ],
                "enabled": true,
                "visitList": [],
                "bookmark": 0,
                "tempPassPhrase": "quickjob609",
                "name": "Stephen",
                "preferredGreeting": "welcome",
                "email": null,
                "lastSession": null,
                "lastUseTimestamp": 1522903417000
            },
            "user": {
                "userId": "amzn1.ask.account.AG4BEMGBJIJYRAGKP5YLYGJDISRIQVPWOEABD3OQW66MTPOF4JRHLAEETH5TBIOT652I3KUYZSWA5MAZ55GUTIBLEMUQ4YQBPKXVG4YSFHLQL27UEC6YQDXTEYH5MD4NMK4M7UJ4FWTRPKTSII4R733EX3TVC3UKLKOBMHXXM5CHOX2TDUV2WPF6NCWF5KLJETNGQ5YC7EOUDBA"
            }
        },
        "context": {
            "AudioPlayer": {
                "playerActivity": "IDLE"
            },
            "Display": {
                "token": ""
            },
            "System": {
                "application": {
                    "applicationId": "amzn1.ask.skill.50ef6df2-ffb8-4692-8e18-c9b485cc03b0"
                },
                "user": {
                    "userId": "amzn1.ask.account.AG4BEMGBJIJYRAGKP5YLYGJDISRIQVPWOEABD3OQW66MTPOF4JRHLAEETH5TBIOT652I3KUYZSWA5MAZ55GUTIBLEMUQ4YQBPKXVG4YSFHLQL27UEC6YQDXTEYH5MD4NMK4M7UJ4FWTRPKTSII4R733EX3TVC3UKLKOBMHXXM5CHOX2TDUV2WPF6NCWF5KLJETNGQ5YC7EOUDBA"
                },
                "device": {
                    "deviceId": "amzn1.ask.device.AFUWNBZ2FSMDFRJDWWA7GSZQBYX4DBS52RV7CHECNUTBCVMT6WW5SVO56SLUZ6D6TIJM5J2S6XNXKHAUU2RCXXQKUI75C37IOPVAA6HCVK5E5NV5EBVC5YUFAMIGD4FYZ4XFA4OEPDNCJYCHXN2RRGDQOZYQ",
                    "supportedInterfaces": {
                        "AudioPlayer": {},
                        "Display": {
                            "templateVersion": "1.0",
                            "markupVersion": "1.0"
                        }
                    }
                },
                "apiEndpoint": "https://api.amazonalexa.com",
                "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjUwZWY2ZGYyLWZmYjgtNDY5Mi04ZTE4LWM5YjQ4NWNjMDNiMCIsImV4cCI6MTUyMjkwNzY5MSwiaWF0IjoxNTIyOTA0MDkxLCJuYmYiOjE1MjI5MDQwOTEsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUZVV05CWjJGU01ERlJKRFdXQTdHU1pRQllYNERCUzUyUlY3Q0hFQ05VVEJDVk1UNldXNVNWTzU2U0xVWjZENlRJSk01SjJTNlhOWEtIQVVVMlJDWFhRS1VJNzVDMzdJT1BWQUE2SENWSzVFNU5WNUVCVkM1WVVGQU1JR0Q0RllaNFhGQTRPRVBETkNKWUNIWE4yUlJHRFFPWllRIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUc0QkVNR0JKSUpZUkFHS1A1WUxZR0pESVNSSVFWUFdPRUFCRDNPUVc2Nk1UUE9GNEpSSExBRUVUSDVUQklPVDY1MkkzS1VZWlNXQTVNQVo1NUdVVElCTEVNVVE0WVFCUEtYVkc0WVNGSExRTDI3VUVDNllRRFhURVlINU1ENE5NSzRNN1VKNEZXVFJQS1RTSUk0UjczM0VYM1RWQzNVS0xLT0JNSFhYTTVDSE9YMlREVVYyV1BGNk5DV0Y1S0xKRVROR1E1WUM3RU9VREJBIn19.SFo_wM9VU_F0V_z4pArPrxInx6thEG40-wwF3Sj_jYZeDp9oWhQuVGlTj-3RfvEDugUGpNNUOaD24ADpm6IKfSNdTLKR8GnYQiPtwPLiQqow3OhyFoOtkPgiBl4m3p7IrojdJ24eZMw2lxIWwBvUhataBt2ZDcsnBLJ9e_U2g4p98CCWDmbP34ieHajsnO33a2c0PNv8XV7k33jpR3QCT8WnqBQrEC4B-14yzeovDhvYs4lvgGJYLR088ODax8Is7bGlgTrW0KqMZOWpJ94klIJGlpWEf2XQe1whHDac2AOcEX6qxL2peQeQPVivMr7tUM8H0JaPTmancqPl76KYlw"
            }
        },
        "request": {
            "type": "IntentRequest",
            "requestId": "amzn1.echo-api.request.b508be09-0107-4f4b-8758-9a4e6578771c",
            "timestamp": "2018-04-05T04:54:51Z",
            "locale": "en-US",
            "intent": {
                "name": "MyColorIsIntent",
                "confirmationStatus": "NONE",
                "slots": {
                    "color": {
                        "name": "color",
                        "value": "crimson",
                        "resolutions": {
                            "resolutionsPerAuthority": [
                                {
                                    "authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.50ef6df2-ffb8-4692-8e18-c9b485cc03b0.ColorSlotType",
                                    "status": {
                                        "code": "ER_SUCCESS_MATCH"
                                    },
                                    "values": [
                                        {
                                            "value": {
                                                "name": "red",
                                                "id": "red"
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        "confirmationStatus": "NONE"
                    }
                }
            }
        }
    };
let context = {
    'succeed': function (data) {
        console.log(JSON.stringify(data, null,'\t') );

    },
    'fail': function (err) {
        console.log('context.fail occurred');
        console.log(JSON.stringify(err, null,'\t') );
    }

};

function callback(error, data) {
    if(error) {
        console.log('error: ' + error);
    } else {
        // console.log('****** CALLYBACK');

        console.log(JSON.stringify(data, null, 2));
    }
}

// call the function
MyLambdaFunction['handler'] (LaunchRequestEvent, context, callback);
