// This is a Javascript test harness that simulates the execution of Lambda function code
// From the command prompt, type "node test.js"

let AWS = require('aws-sdk');
AWS.config.region = 'us-east-1';
const tempPassPhrase = "sweet-dog-721";

const MyLambdaFunction = require('./lambda/index.js'); // assumes single Lambda function with exports.handler

const fs = require("fs");
const myFileName =  `./lambda/helloworld.mp3`; // `${__dirname}/helloworld.mp3`;


const myFile = fs.readFileSync(myFileName);
const myFile64 = myFile.toString('base64');

// console.log(myFile64);

const stats = fs.statSync(myFileName);

const fileSizeInBytes = stats.size;
console.log('mp3 size is ' + fileSizeInBytes);

// saveFile(myFile, 'abcde.mp3', function(result) {
//     console.log('saved, result: ' + result);
//
// });

 // this is the Lambda request data, generated by the Alexa service.  Replace with your actual Alexa request.
const lookupTest =
    { "queryStringParameters" :
        {"tempPassPhrase":tempPassPhrase},
      "path":"/lookup"

    };

const updateTest =
    {
        "queryStringParameters" : {
            "tempPassPhrase":tempPassPhrase
         },
         "path":"/update",
         "body" : {
            "attributes" : {
                "namePronounce": "Leah Danielley"
            }
         }
        , "file": myFile64
    };

let context = {
    'succeed': function (data) {
        console.log(JSON.stringify(data, null,'\t') );
    },
    'fail': function (err) {
        console.log('context.fail occurred');
        console.log(JSON.stringify(err, null,'\t') );
    }
};

function callback(error, data) {
    if(error) {
        console.log('error: ' + error);
    } else {
        console.log(JSON.stringify(JSON.parse(data.body), null, 2));
        result = JSON.parse(data.body);
        // console.log(JSON.stringify(data, null,'\t') );

    }
}

// call the function
MyLambdaFunction['handler'] (updateTest, context, callback);

function saveFile(file, fileName, callback) {

    let fn = `mp3/${fileName}`;

    params = {
        Bucket: 'skill-images-789',
        Key: fn,
        Body: file,
        ACL: "public-read"
    };

    const s3 = new AWS.S3();

    s3.putObject(params, function(err, data) {
        if (err) {
            console.log(err);
            callback('error saving file');

        } else {
            console.log("Successfully uploaded file to S3");
            callback(fn);
        }
    });

}

function returnSample64() {
    return `//NgZAAAAAGkAKAAAAAAA0gBQAAA0XJMCaaCA7TDaSKvx8UEO+Sch7K548GR4l/58oxD//GoqKoWPM///IEzhYJZgrLlv//3+1xuD8mNJIgOlB8wt/////nmow+KCxBHHfoKtBux2RJSATfWYBBxkLTwK1O/rOehXKyeGJZjr9cwm5+5OQ3aqXwJoFICtjBAegwIjZLEAlDArM0F//NiZIcJoX0gAMacAIAAA0gBgAAAUXUty8tEkDxTLhPTZMrKZgaHicTy8IwUU3NjIuMm7Jl02SQPXVRmR1BN2bSZT3QdPvWq7Je79SCLL1L39Oxg7VOihWyTLQTZ7KdbGCN1roIGS7RnCHEfxQAsJndpZfuBgwHSbVgGDr0Ml1/jG2zEBRgwMADBSds7shkTnEv2sZ+AsFAaAKSSwv/zYmTCEjltMy/tNACAAANIAcAAALIh9F04tOlQ7pcAiaGrEUFLNW9rmfGKARXDgEXIiFSDakxBTUUzLjk5LjWqqqqqqqqqqqqqqqqqqmGCGoKt4Q4UpjVr00nFGLz//t5hJtcjLMWoA763YdE5708yu1cFTeYMBe5pB2cKlYQLslp0R/cKHhJk24HnLd+u5DVUmfOGNe9CiDTPv3T/82JkuAoMfUMvKSMEAAADSAAAAABLA6t9nK2zNl14PzeP1WUYTEFNRTMuOTkuNaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqmqupFJYZGkCJE5wBnz9733/OZtoJJ1JIH3YMoUcSeUnFvWt8DyaBnciWVIlIVCbI5FNNJclbf8i5xk/8tX7ZWRjHa36o/f36Z9Vzy3e//NgZNcL4LkoKjzDLoAAA0gAAAAAqGvdiOz6tFQEYjwmL+zt1UxBTUUzLjk5LjVVVVVVVVVVbACGKAoCRqaEAoAXNQuR04mk+G/DVHgqH6muoqhTt6xSiKciMkPN8xNVY0gtzoOlVP1+iZBBhVCelscUTZySLW7aJWZwepJ+5KrcOA9eNPyOESakOaw6bdj7EFKvPJ8ur2cBEsmr//NiZNQLhXEqexhlqIAAA0gAAAAArvcO32WzO01ki0IbN9JZ86pMQU1FMy45OS4kAqQxbJxIlIYG2djDh9C2KVms8WshZl/Wt8JNmI3cX7VkjYgMM6Bb08UZpD1GIIQX1FHBDh3cqubjDmsgBBbFDA72U2gm1TLWPp6c7ulGVubOTlFpn16bdKfGdseXIXuF1PPjan69z880ucaKb//zYmTuDsVzHhYkZuSAAANIAAAAAPN3fG7Kr9v/272mRPzAjbyFTEFNRTMuOTkuNVVVVVVVmhs5fEAiCeHBNH3mm711rH1jcLWN1z4Tk+xO/Vb2mrNcW7dR6pjSyfyiVSgitQygJ80dHRNiG5Kug30qWECS0WG1ULpzWIKg1BO26nPdoxX2Zxt5eGZZG+l7bR9mz/lTstiThTu0PYb/82Jk9g/VcyAaJeaiAAADSAAAAADqUKcM94pnqzChyGuG34cqaIQtBNWI6gN5ZJ58/x4F5qRY0sOHq+Zb722wmBziXVrijFSzvmvUJrlfvaxJFczGuiy6ErAzBPNLYrnONAa4O43pG+k8Q03t6zMQlIyMgxMofYJGWV1dEh3MAIxbtdJSVr04TxGdyIcFFPB9U1oHDxlfDwIb44uQ//NgZPAO5XEeAD0jtIAAA0gAAAAAkFGMR02avj7CTKQhVxpKouMqCBDIFDhCeC4I1KNyddQaeBFgezq+8wWpe1rQ1M3Dk39Cy7BMI3Rvafe44xa6g1HIDZNHYilWC6iu4yyu7EcBCCAS8Dx6YAs4GsIQI4YifJUUBzcVGNZqjIfweT1Vu+0fT7UynB2YzZWkQQorZu9Zj3Sq+yOv//NiZP8RKXcaAD0jwoAAA0gAAAAArdH43y23sdusVzNXASQJcS33BylGGXQcQEgUpcXyHIhbgRYVMvXzNlqizNtGW7Dim5WPCuZGJWyLqTqxM31d7MpApHkkqTkKIUWgaWQSRE9oTck18gLAIOaojVBJo21BSEnWf8bvpTpvzU5KISzr0GjCir1miEJWyGY2+dn4wgxTPQEGvtOmzf/zYmT9EN11GhI9hlyAAANIAAAAADZj03rnVE1jJMe0wKJlCqIleJA2hhGmXuRz6rEpgcfMxNxlmSeA88612zrGxM8uXfzJTUbSSISRDMlRoEYjEAlhBgnMXIiZl8jBdemS5tyAxBJ7KN8INLvV2lmxSlaya6YpTvJxTCECUSs78rQbJKaWYUq45ehghSTclHu1/ff18iMaHhmZjRD/82Jk/hINixxmPMmsAAADSAAAAABJ+t6qE2/mXqBd6VZIOZnxG23dm0aS2UthVRCWU8QkWNOPEOiIBUx3P4hQNRN6+N5tmEiOkKSrmZmELJkQsMoEFoTWsx0SrETR0fZgqDxA5SW6b1hXrWzIHarkzKzJvo5wSco8lxOb1ysEGu4jNvdnd9fDw1ygX9O4OvdMamxlPinacamd3rVa//NgZPUQxYcaAGEmboAAA0gAAAAAt3lmLnxtnJWlsfyXePtXUY0oxRpXMKrKTEFNRYA4gE0JQDAtqGKMyHMKHNzOiViCBB919JoIZG+KLEMcFCDSBNGwGOBCGIExLF5I02NIoFC051ghjaZHNaDxW9ZbHZqNyiXDoz/OmRztff9t7xsy58Pr47XdPRU1SxEM726mjK1ruF/z/D+b//NiZPUQrYUaET0mfoAAA0gAAAAAXq5YwxyK8Kd5jO/M9N1T0rV6XHXwAxWPtDT4S8lcCVbeNNWuWJmpVr15px4PpaVIyqOlzcRlv1ZVjyiP/YTunQZEAkq1p0tqtTsLre7lyZCuSMtncNKr/rdeihMxeeFQs5G5LbV83PMqOQHFDmEpY3M22HnLdRA5qcWeVl+Cjw+PX2Q4OkzpG//zYmTzD3WFHBIx5gKAAANIAAAAADuX3JvGnVVOd4nVIIQ1smbNnIEll3OFVL1DpAASoEGKi9GWjIbthpzaRI+Ba9q3lly3b+INHeZ5lZYk0ON3i1k80mM157ZIRGfUTDZfZ5dXFhiZ5haXnPBhKMWNAKhvIZ/eFRqyxPFkSXfEcP3JddyAbRiro7q62MDgkYWA7hEgRCyr3s//fTb/82Jk/xJhdxoAZYZ+gAADSAAAAACC8pxCisTw9Q5DN+zebfj9XGO1I3iReYYtU230vkNSRQqQwuSdYVUCx3AIlNIhW9V76wCFEnZI4bM2ny1KgIQyxl9PT2pZzC1Xp7fWsOYtNW9+pLPVbOMvIYY8H7o/FrZgvIOMhL8cq17S9tR0MO/h4t7he0S64re0IMFJAUBQoGs6yQKkBvAH//NgZPQRcX8iemEmeIAAA0gAAAAA5kIBHX9v//Smd6+a0fHQ9vLJRpLoaze8maVBNaW/AKztHJKAwNYIwQCCgoZgdGWCQkEmBhYXCDOzEDE7nDhycnPmawRpBQQCIXCjCwlGJpjp0D2Q4yiEiwQYSLgoCMQBhCKmNhsDQ5SWp6NtxAVUed/kj409EiLGCkqe50NcJfNxW7Hx83aK//NiZO8QcScmZGEPqAAAA0gAAAAAZPV/xf/+/8WxFnxi8JtLZEPkJOpjUJIDxCHJQ5Or2fN7x3jyI8iv39761nMN/Pf6+PrX+aQIlHlHgLhgEBa5lbqVRFmJyO2xDoGVXbcjExYeDItNWjfIwKhDM3ACzmeuGjoajMOBwkUhivP0a2gKKhw/M05MFG9HA0bICTBBECCD9k1VdKCJnP/zYmTzFZFTQS9tD5gAAANIAAAAAGMa/8DXxf/fzfT8v75n3JaJTUJ/q+vaJTwsZr9IhULhKkzEzMxQuaHxol9f3nOx1D4waNcTEhwfD4agkQONb27HOPOHBxGaT9J1/HFLIAgAAkB38EIkgQC7JAHAPxuSkdPIjZ+AI+WyU4z0kqHgGiKDBwYGw5PrfMq5RH3mL7Vebo3iluW9y6j/82BkzhNVYVEvbeWKgAADSAAAAACx7qN0X/g68538s8NYzMGSy1HFPJiQJfxl1LW1Kce71hQTnPyy1rOSNxZI4jtS8KDhw8niT/Z3tf/kZaZgSizuYMRGKlN+WPFkcgqLsnRVlb99bsGu77skCAeJ0a4BidS/KGZjbpOk6kAyAbcgAw7nWlI6rf2kp2jGJtwzcznRJeoFQwwvlSX/82JkuhNJd1kfZEnjAAADSAAAAABFblUHApJQ7wdq1S8zBbf8msRJT/g2zWDFr6V+PhJsMCAxlnLXMrNG4f/j//y7/BQaHx0//x8vddoqye8yUEAcicYJAIB0aNMFz1muVWEHKSaD4Ng+tP///9O1Ux3FgPFG+KzlgBAA3QEsZ8nzEFyInRUKxTsKCIlCXHEAY5BoOCTrcACPevC7//NiZKcQVVlQ3mnoeAAAA0gAAAAA4jBFDXGolWYcKi3LL3H+3/aveVJUvnBz6d9KK2LpnR2EBcCh4XIokOOcXuhP/V6JOdDoHEZXBmJfzMzk445H6dxayhq1561h4QQqHIazclKBNK6AsPjo0i9+JqBkeUI6W3eUNeerXwxzd8wDQWfWG16q1QDrIAEA/W4AIDzzU76DoMMlxyVoyP/zYmSsEskvTNlorKQAAANIAAAAAGewEgGG2fl7wNgca3aQwR1QdeFnaIphxQNAQJDb0YzDmUWIBbEaxYxDfau8i43jPix82e7Z04Sxaht8dUxr0p////8YopD5LsTZGLB7xaY1vP/+c1hZ9av1+HiNKxNeGI/jqZkmcL6Fl1Sauvjf1p7UEjPZaN/9fYerybHeghkGMfQqiAAABuT/82BknRLldVIvaeKOgAADSAAAAADADwHNXWwEA53sFhVbZ6rxGDjGXGlScgeB+alRkEDZStr7y1X7eRusZrwXlwokJIOuYAA0KTp9e0wsbsP2eiaDY6Dx+v86PDwqEUfF42ov/WptzXLjh5acJxMKkEphw00wma5t6t+ym33X/6I6nFiorFiEjxwSyg0BwYcuRdMA0oQHQP+vaJr/82JkjBBdd10vYMeGAAADSAAAAADX7YyNyn2pxEInk2KgERhG1jkcgyUxWULQUtoaJ9XKhqMV5imQKS3VemLfIzez6/FkCRkrdkFvnqrw+Zzby871DFFMEDqXv/r2MBLODDylCDICAwsUdLN/////RTXiYcI7EBNR3qqwABAy6xOXAajsOKGERqXNJXtd8RC5k1WWonMG+KQqmpwM//NiZJENxWlaL2DCiIAAA0gAAAAAcqUNG4pM1Bxpsc5FtLTd7XvQewMe7KUYPvj0I6WRE/OAJGVU//1sPdTMyGESqxg8LKUyVpT////7MbahjFaguiqFAApSyxyTAYymCMWwUYF45+fJimMDgsOFLfB6b4d6YufurDp9zJnlWjHNq5Rw4VdxUyiTXN/qb+QxRIaT/9nW2JIo6rEEyP/zYmSqDElpYy9hBWoAAANIAAAAANIhRrNv/////1qVXCjGGCa10BVMQU1FMy45OS41VVVVVVVVVVVVVVVVVVVVVVVVwAADsuTnwFm08ICDis84JHauzowyW/X410SAahAdMjXI9PoFAppzCQzx/iJgZHXRzU8q/2j2xantzOz6PKUjqVCogyongjhgJj2//6M5QElykFFFzXVRrF//82Bkzws9ZW0vPMU9gAADSAAAAAD9Jn//ldDPdUMqzTGFthIqTEFNRTMuOTkuNaqqgC40XKBWlD9m0AjUaEkBgx/0aBtXEDkxpRK1MowYwzgZzoYMAiabByCIIAK4lMhvhaqHKbr4p5tidSHm0OH7D4f1Z69GsZUCx3QR/GlzNfSWxkEgYcc4uK+//0Ua5jKMIYXAgfQwk5ClonT/82Jk4A0FZVTfZMJogAADSAAAAAA32q3+jDSKIHL1qfuS8fsFmkw6RwpplD4wCqi3y6QgBGAW8IwY9yOJqKemiQG+kDGehMYiBijJeY5U0W4IMWg/DjOKZaISgUfIHJeNv8Jp26epZZZFJsLgsveePyKWywPD+PJYws6mdPQlqObM4mSyqJi5UGCZEui//Mo1B804yZwEFCoRv/////NiZPMPcUNGb2mFdoAAA0gAAAAA86yEbFRh0blVGR01HB8RHtU1gLB85kBS0GFR/UyTC5uAS4GgWYPBhhtaHOzONAsuwY5JBpASDwcUGHQocidNYQ1ug0N0BGxwEnCY8aEB5GyhYdx4+/CmjXHcXOXcEgoGAtkh+WcxaW8jcp+djnZn07FdiiwjIOZ0A4nu3/+thJ3QTMHXHnDqj//zYmT+EM1zQApzJVgAAANIAAAAABdR////9WHkOhhoqLqcVchUug176BR+1XizUGOV4qgjEh4GoSQMakO6UUJRxn+C+0hHnBwIiExiFu6kRKVFFhhCCesn57lxBpwPVTLC2cR3rxeSCnQo/TFY+J9/yYr8RcMk+M3iQtSf/////VsSRT2VDiTUMgVSDSLk5uebY//X5Q6hjmBg6Qv/82Bk/xHJbUIOc0VYgAADSAAAAAD////0TRxch3O6SKxE6CjTCBSATszDABCBSAYY5oNBDBF06NDWDEZIYe4HO4BnNmeUuFQxgTBjA6n2HozGBECq0zYsv+YMgaq6YD4cpwCjIEBrwLtu1Em8QaTLUPL6gYSsZOhwZhucUAjBHH8vhn+991FxzdV//y3dxfBW0gksNki00ayq4/3/82Jk9xAhbVAOaeV9gAADSAAAAAD3ykibxtinWakszYhRQ+ULiv/////////tK3cOek22wwnb4OmTEFkVvWqpgAGp83bcN7aphkD7ZlQVqRHA8dUZgTQ6M7ph5qVOqguZ0r8dlvPrGV3HvWDmvtnGX8s1Hev96AHYMcl6rpHhsdqwM//zV/8/PvKCYPBqbEyVT8Ml7/3s2aadq59E//NiZP4T7XVCDW9LSgAAA0gAAAAABsURyCQikbFw8E285JQOwdfMIGlLV0Y7//mdLvKdXsdQbXYqBndhAhWECaACTj8as1DRglN4+yr3gIRBKiSOU11L0/H0CcfeZ9l/hwGoAVSNuwWceVu8cpsJp54mse1GOOpRUedc6nysiLSFgyLB5WXqv2Vtj///3WkCUTxoD2bprKINKb7GYv/zYGTmEM1zaR89YscAAANIAAAAAJRJZQKBB46JGd2MLCzdHzdDgMHhyKv/6NMLEYgwPD1SIlfJeVjFoaAGUflYh5c5groOEL2V6om8xsFqQzmLAgZYdPEPcl9wJihJQmrhh0RgAKYS4Wk4z8RiXulQEUpUTOVEovc87PT2VxtONqZs07+2MMWGt8///1BQC4fB4HwDqgJJakO4nP/zYmTmEJFnVK9lZYoAAANIAAAAAL1dUYqlHLiCJx5ijx9VqzrHVTiTDKc49E02HOViqxaO///QWmCTKpA6WLnTjOVGKgCrAKgZboouODH/gECuggsDBwQqYoiDSZzAjCATKTWc2KvxKUrJdEYKOGomBfZ+4ZpZc1dpOIR0OeidbtVMqdcTEXCR5b5VO/7WOKmOu///+dw2kKBktEL/82Jk6RIFZ0hbaWWOAAADSAAAAABsXw/r973Q1pWsaxJ4SzJfqoe+HGt/jGxTf/7kM5RLOwUuQVNRVYAKmABANWrIui6oSrCwJYIybSsV5QA1gAkvUF/OexLXmGEgxgjNhoyFeDyxxxZ7vM33Y4wRBcvRNdERLRP+K/m9JdKn/lywEwfGCiC4f2WLnoHANA8IMPcXZBVIMLHswAAE//NiZOAPpW9EK2VijIAAA0gAAAAAO5+Ppeqncjdf//6nFpIy3PdAMDfAZzPAFYAEHkYA3o8rMiCcNCOSxpHCmzaTJ8O2Ef0lPEtJeGdp4oJwbI8KzNDW4qa5hTtcr/d/e4ypFjaVw6JZo+7/4qK/+pGA1BqKhCHQNgbKSSaIR0A8LiwTirhyJrWCaoo6xo4r6/4uGc3KsUliIvnD7P/zYGTqD0ltSK89AoyAAANIAAAAAD9Pzb7lm3VkKN3bnJZBbfJ6kqNrIbwj0iYD5U7hVPC8tdKLr4+qpj1MQU1FVVVVgIAAD2bASkEidC0g8x+izEs3a4uHzCAXUxbdr1TzanVQCGqX01ds+pp/Y4JxO+jJAFT1O0jOGlMoYUKeX/Dzb/sp1OeJ6l8xbBkbIv/IMprCgaq4PdWKvP/zYmT2EuGPTM89DI4AAANIAAAAAKrckaCLwVMOKhMJBQGodIxiTEFNRTMuOTkuNaqqqqqqqqqqqgArHCFLRXaRC5VI+VessmWM225nowiaucMWH5S7RqD9QR1pj9l/MMx3rKQyu6kxhg0936lcwe2QaMExFEnEta/K4REQKikY1WQxZRW7GL6OgxerzF6bWyiR3sZ01VBrJ0VLiYL/82Jk4A0U80svPYMeAAADSAAAAACIqyCVSmdwiw91Uu2pWFTZ6kxBTUUzLjk5LpQJS5+nmDcBjHqjS3J1SssdTocnBvGXHWeALQ5ToQotx7grQ7jIexKEQtMDM3MzQ+bOp3splGbLNUk362RMn0V0ETJJBaZ1SK1oP7Ow8iRNHY6vmJjJhTODmZMoTBruzmKC2NUUup5iqka236lf//NiZOwOiYdEPz2FVoAAA0gAAAAAXQdPen0zFH1JL61HTHnmVSkko024Q5G3Gmy3AkAPnY4XsY0h2llkMMYUK5hhi+R5OG1TLgYtNLOVK6aPYBG0hbUwQ2B0i3uBIsx5cHH03gMCLxSafzxOkW7BUXLgsmy1vX93nuk3fxwq0im1eJy+kmaSmf9kbJwwBCds7iWV+inYrEedt3rXzf/zYGT2D6VrMgmntAAAAANIAUAAAE9QydYgkPo5BheqTEph2IxXWN2l7yzf5lrV3ve7yqTnecz1t+5/PfX8llWh7lzCJT23f8IYnO8zqChACYDJANbPYXIyqEyANgE40UJQlSxemT9ca0jNWN2wcAdBGUH1jLWWZu4yRU0Z99VFSjXIqt18bqUPa6rb6/j+1yi6Tn+TdUXlrn17/f/zYmT/Fj0pSS/M6AEAAANIAYAAAKv4/5/5HkmtQ8+mMDBIVM1vsrpuBU6mcShdCjRp6sS2fr4ghVjnRSSFiYjqrmVzAaIqCBQqAuVRxWWMjo7XxOFL1DD6aztYUUsRwXaZclk5jMs5LC20Ql1yqfzdchqSr0rCVZ3fjZa8UoMT1l1WF1NkDxh7XVbelscBFjf27t33ddkdWajc+Xb/82Jk1Qx5FTo756AAAAADSAHAAACJ7t/Tvdszf58+MeosVXIK0VndEVUUU3VMQU1FMy45OS41VVVVVVVVVVVVVVVKJLB9a1rmOj0AEgnvMu13LklxfLlZE+DUpRmUrjY2LBh0nEv3l8rcJLlmqZ8otTbMkSJRK63vOVrTBLZZ5aTiVPjVUzhywUJb+f8ZL1hyXKuqrOiVYFcColEI//NiZPkRDVUgAD2GboAAA0gAAAAAqAgKRBrjRgFCR4SiLriVykxBTUUzLjk5LjWqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqgAiFJdh8ZKrLJqTzc37FplEKREDoHAcNkBOYey0hVSXYa2IyPJgcA5VSVdNNNNWn0wqqqqqYav//hNNQ5YJoiLJStUyxWjSwTTUOShNERf/zYGTjDUzxHAAx5mIAAANIAAAAAJKVqHLLUVLJab/5WipZLTVMQU1FMy45OS41VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/zYmTWC8xs0AkkI5CAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU=`;
}
